# Generated by Django 4.0.4 on 2022-05-02 16:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image_height_article_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
