# Generated by Django 4.0.4 on 2022-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
