# Generated by Django 4.0.4 on 2022-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='DOB',
        ),
    ]
