# Generated by Django 4.0.4 on 2022-05-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='author',
        ),
    ]
