# Generated by Django 4.0.4 on 2022-05-03 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
