# Generated by Django 4.0.4 on 2022-05-03 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_cv_summary_alter_cv_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='title',
        ),
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
