# Generated by Django 4.0.4 on 2022-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_cv_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
