# Generated by Django 4.0.4 on 2022-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_cv_address_alter_cv_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone',
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
